#ifndef KEYWORD_HPP
#define KEYWORD_HPP
enum KEYWORDS
{
    /*
    * Range of values:
    * int:–2147483648-4294967295
    * short:–32768-65535
    * long:–9223372036854775808-18446744073709551615
    * byte:-128-256
    * boolean:0-1
    * var:auto
    * The interpreter will auto set the variable is signed or unsigned.
    */
    TYPE_INT=0,
    TYPE_SHORT,
    TYPE_LONG,
    TYPE_BYTE,
    TYPE_BOOLEAN,
    TYPE_VAR,
    TYPE_EXCEPTION,
    TYPE_TYPENAME,
    TYPE_STR,
    MODIFIER_PTR,
    MODIFIER_SIGNED,
    MODIFIER_UNSIGNED,
    MODIFIER_EXTERN,
    MODIFIER_GLOBAL,
    MODIFIER_LOCAL,
    MODIFIER_CONST,
    MODIFIER_COMPCONST,
    KEYWORD_SCOPE,
    KEYWORD_INTERRUPT,
    KEYWORD_NEW,
    KEYWORD_DELETE,
    KEYWORD_PORTIN,
    KEYWORD_PORTOUT,
    KEYWORD_REG,
    KEYWORD_IMPORT,
    KEYWORD_FUNCTION,
    KEYWORD_CLASS,
    KEYWORD_PUBLIC,
    KEYWORD_PRIVATE,
    KEYWORD_PROTECTED,
    KEYWORD_INHERITED,
    KEYWORD_FINAL,
    /* def:define a macro */
    KEYWORD_DEF,
    KEYWORD_EXPORT,
    KEYWORD_RETURN,
    KEYWORD_THROW,
    KEYWORD_CATCH,
    KEYWORD_SIZEOF,
    KEYWORD_TYPEOF,
    KEYWORD_CALL,
    KEYWORD_GOTO,
    KEYWORD_IF,
    KEYWORD_ELIF,
    KEYWORD_ELSE,
    KEYWORD_SWITCH,
    KEYWORD_FOR,
    KEYWORD_LOOP,
    KEYWORD_WHILE,
    KEYWORD_KEEP,
    KEYWORD_END,
    KEYWORD_DEFINED,
    KEYWORD_SWAP,
    KEYWORD_STACK_PUSH,
    KEYWORD_STACK_POP,
    KEYWORD_TYPECAST,
    KEYWORD_DISABLE,
    KEYWORD_ENABLE,
    KEYWORD_TRANSPARENT,
    KEYWORD_ENUM,
    KEYWORD_REVERSED_ENUM,
    KEYWORD_USING
};
#endif